M48
; DRILL file {KiCad 7.0.7} date 2024 February 22, Thursday 14:50:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-22T14:50:12+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X50.93Y-76.5
X50.93Y-101.5
X102.93Y-76.5
X102.93Y-101.5
T2
X52.5Y-82.5
X55.0Y-107.5
X100.0Y-82.5
X100.0Y-107.5
T0
M30
